### PR TITLE
playing and paused classes are flipped

### PR DESCRIPTION
**Pull request by ptmkenny**
Hey, I'm very sorry about this, but upon testing the new release, I realized I flipped the playing and paused classes. 😥  This PR fixes that.

### CODE REVIEW

**Comment by lhz516** [comment]
The class name is more like button status, not audio status.

When the audio is playing, we are seeing the button with Paused icon.
When the audio is paused, we are seeing the button with Play icon.

We can update the documentation, and not necessary to change the class name.

**Comment by ptmkenny** [comment]
I was thinking that the class name is the audio status, so I assigned the names `playing` and `paused`.

If the class name is supposed to be the button status, then it would be better to name the classes `play` and `pause`.

`playing` indicates "the audio is playing now", and `paused` indicates "the audio is paused now" (so `playing` and `paused` suggest that the class describes the audio status).

On the other hand, `play` indicates "press to play", and `pause` indicates "press to pause" (so `play` and `pause` would probably be better names if it is the button status).

**Comment by lhz516** [comment]
Ok, I agree. I'm merging this. Let's try not to bring breaking changes in the future XD.

**Comment by lhz516** [comment]
Actually let's consider this as a bug fix, so it's no longer a breaking change.

**Comment by ptmkenny** [comment]
Yeah, I'll do my best to be more careful.

I agree it's a bug fix because the classes didn't do what their names suggested.

**Pull request merged**
